### PR TITLE
fringe: Add description for mgmt event

### PR DESCRIPTION
**Pull request by purpleidea**

### CODE REVIEW

**Comment by toshywoshy** [comment]
Two points to change :
1. Add a new param type "eventdate" with the date "6th February 2019"
2. The registration is meant to go through one system, so I added your questions to the registration system, take a look on https://registration.cfgmgmtcamp.be/ghent/2019/ and link to that

**Comment by purpleidea** [comment]
@toshywoshy Voila :)

Thanks for making the reg form! Can you increase the available mgmt count to a large number please? Maybe like 2^63-1 ?

**Comment by toshywoshy** [comment]
Unlimited it is

**Comment by purpleidea** [comment]
On Tue, Nov 27, 2018 at 10:29 AM Kris Buytaert <notifications@github.com> wrote:
>
> @toshywoshy am I looking at the wrong places .. coz none of the fringes seem to show up in the public site ...

I think he said somewhere that he was waiting for them all to be added
before adding a link to the main page.
Click here for direct link to see: https://cfgmgmtcamp.eu/fringes/

**Comment by toshywoshy** [comment]
Yes, so as @purpleidea already mentioned, and I thought I send my explanation to the ml
I will add the fringes to the top navbar once more have been updated with content.

**Pull request merged**
